export const VOICE_LANGUAGES = [
  { code: 'en-IN', label: 'English', native: 'English', script: 'EN' },
  { code: 'hi-IN', label: 'हिन्दी', native: 'हिन्दी', script: 'HI' },
  { code: 'pa-IN', label: 'Punjabi', native: 'ਪੰਜਾਬੀ', script: 'PA' },
  { code: 'mr-IN', label: 'Marathi', native: 'मराठी', script: 'MR' },
  { code: 'bn-IN', label: 'Bengali', native: 'বাংলা', script: 'BN' },
  { code: 'gu-IN', label: 'Gujarati', native: 'ગુજરાતી', script: 'GU' },
  { code: 'ta-IN', label: 'Tamil', native: 'தமிழ்', script: 'TA' },
  { code: 'te-IN', label: 'Telugu', native: 'తెలుగు', script: 'TE' },
  { code: 'kn-IN', label: 'Kannada', native: 'ಕನ್ನಡ', script: 'KN' },
  { code: 'ml-IN', label: 'Malayalam', native: 'മലയാളം', script: 'ML' },
];

export const VOICE_COPY = {
  'en-IN': {
    title: 'Speak to DirectFarm',
    subtitle: 'Search nearby produce or list your harvest by voice.',
    searchMode: 'Search produce',
    listMode: 'List my harvest',
    inputLabel: 'Produce name or voice command',
    placeholderSearch: 'Type or tap the mic. Try "tomatoes".',
    placeholderList: 'Say "20 kg spinach at 40 rupees".',
    tapToSpeak: 'Tap to speak',
    listening: 'Listening — speak now',
    processing: 'Understanding your words…',
    successSearch: 'Searching nearby farms',
    successList: 'Harvest details captured',
    errorGeneric: 'Could not hear that. Move closer and try again.',
    errorDenied: 'Allow microphone access to use voice commands.',
    errorUnsupported: 'Voice input is not supported here. Please type instead.',
    errorNetwork: 'Voice service is unavailable. Check your connection and retry.',
    stop: 'Stop listening',
    retry: 'Try again',
    examplesSearch: ['Search tomatoes', 'Find mangoes', 'Show rice'],
    examplesList: ['List 20 kg spinach at 40 rupees', 'Sell 50 kg wheat 25 rupees'],
    confirmList: 'Publish harvest',
    editHint: 'Check the details, then publish for nearby buyers.',
    name: 'Produce name',
    category: 'Category',
    quantity: 'Quantity',
    price: 'Price per unit (₹)',
    unit: 'Unit',
    live: 'What we heard',
    languageLabel: 'Choose language',
    moreLanguages: 'More languages',
    fewerLanguages: 'Fewer languages',
    idleHint: 'Idle',
  },
  'hi-IN': {
    title: 'डायरेक्टफार्म से बात करें',
    subtitle: 'आवाज़ से पास की फसल खोजें या अपनी फसल बेचें।',
    searchMode: 'फसल खोजें',
    listMode: 'फसल बेचें',
    inputLabel: 'फसल का नाम या आवाज़ कमांड',
    placeholderSearch: 'लिखें या माइक दबाएँ। जैसे "टमाटर".',
    placeholderList: 'कहें "20 किलो पालक 40 रुपये".',
    tapToSpeak: 'बोलने के लिए दबाएँ',
    listening: 'सुन रहा है — अब बोलें',
    processing: 'आपकी बात समझ रहा है…',
    successSearch: 'पास के खेत खोज रहे हैं',
    successList: 'फसल की जानकारी मिल गई',
    errorGeneric: 'आवाज़ साफ़ नहीं आई। पास आकर फिर कोशिश करें।',
    errorDenied: 'आवाज़ इस्तेमाल करने के लिए माइक्रोफ़ोन की अनुमति दें।',
    errorUnsupported: 'इस ब्राउज़र में आवाज़ उपलब्ध नहीं है। लिखकर खोजें।',
    errorNetwork: 'आवाज़ सेवा नहीं चल रही। नेटवर्क जाँचकर फिर कोशिश करें।',
    stop: 'सुनना बंद करें',
    retry: 'फिर कोशिश करें',
    examplesSearch: ['टमाटर खोजो', 'आम दिखाओ', 'चावल ढूंढो'],
    examplesList: ['20 किलो पालक 40 रुपये में बेचो', '50 किलो गेहूं 25 रुपये'],
    confirmList: 'फसल प्रकाशित करें',
    editHint: 'जानकारी जाँचें, फिर पास के खरीदारों के लिए प्रकाशित करें।',
    name: 'फसल का नाम',
    category: 'श्रेणी',
    quantity: 'मात्रा',
    price: 'प्रति इकाई कीमत (₹)',
    unit: 'इकाई',
    live: 'हमने यह सुना',
    languageLabel: 'भाषा चुनें',
    moreLanguages: 'और भाषाएँ',
    fewerLanguages: 'कम भाषाएँ',
    idleHint: 'तैयार',
  },
  'pa-IN': {
    title: 'DirectFarm ਨਾਲ ਗੱਲ ਕਰੋ',
    subtitle: 'ਆਵਾਜ਼ ਨਾਲ ਨੇੜਲੀ ਫ਼ਸਲ ਲੱਭੋ ਜਾਂ ਆਪਣੀ ਫ਼ਸਲ ਵੇਚੋ।',
    searchMode: 'ਫ਼ਸਲ ਲੱਭੋ',
    listMode: 'ਫ਼ਸਲ ਵੇਚੋ',
    inputLabel: 'ਫ਼ਸਲ ਦਾ ਨਾਂ ਜਾਂ ਆਵਾਜ਼ ਕਮਾਂਡ',
    placeholderSearch: 'ਲਿਖੋ ਜਾਂ ਮਾਈਕ ਦਬਾਓ। ਜਿਵੇਂ "ਟਮਾਟਰ".',
    placeholderList: 'ਕਹੋ "20 ਕਿਲੋ ਪਾਲਕ 40 ਰੁਪਏ".',
    tapToSpeak: 'ਬੋਲਣ ਲਈ ਦਬਾਓ',
    listening: 'ਸੁਣ ਰਿਹਾ ਹੈ — ਹੁਣ ਬੋਲੋ',
    processing: 'ਤੁਹਾਡੀ ਗੱਲ ਸਮਝ ਰਿਹਾ ਹੈ…',
    successSearch: 'ਨੇੜਲੇ ਖੇਤ ਲੱਭ ਰਹੇ ਹਾਂ',
    successList: 'ਫ਼ਸਲ ਦੀ ਜਾਣਕਾਰੀ ਮਿਲ ਗਈ',
    errorGeneric: 'ਆਵਾਜ਼ ਸਾਫ਼ ਨਹੀਂ ਸੁਣੀ। ਨੇੜੇ ਆ ਕੇ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    errorDenied: 'ਆਵਾਜ਼ ਵਰਤਣ ਲਈ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ।',
    errorUnsupported: 'ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਆਵਾਜ਼ ਉਪਲਬਧ ਨਹੀਂ। ਲਿਖ ਕੇ ਭਾਲੋ।',
    errorNetwork: 'ਆਵਾਜ਼ ਸੇਵਾ ਨਹੀਂ ਚੱਲ ਰਹੀ। ਨੈੱਟ ਚੈੱਕ ਕਰਕੇ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    stop: 'ਸੁਣਨਾ ਬੰਦ ਕਰੋ',
    retry: 'ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    examplesSearch: ['ਟਮਾਟਰ ਲੱਭੋ', 'ਅੰਬ ਵਿਖਾਓ', 'ਚੌਲ ਲੱਭੋ'],
    examplesList: ['20 ਕਿਲੋ ਪਾਲਕ 40 ਰੁਪਏ ਵੇਚੋ', '50 ਕਿਲੋ ਕਣਕ 25 ਰੁਪਏ'],
    confirmList: 'ਫ਼ਸਲ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ',
    editHint: 'ਵੇਰਵੇ ਚੈੱਕ ਕਰੋ, ਫਿਰ ਨੇੜਲੇ ਖਰੀਦਦਾਰਾਂ ਲਈ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ।',
    name: 'ਫ਼ਸਲ ਦਾ ਨਾਂ',
    category: 'ਸ਼੍ਰੇਣੀ',
    quantity: 'ਮਾਤਰਾ',
    price: 'ਪ੍ਰਤੀ ਇਕਾਈ ਕੀਮਤ (₹)',
    unit: 'ਇਕਾਈ',
    live: 'ਅਸੀਂ ਇਹ ਸੁਣਿਆ',
    languageLabel: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    moreLanguages: 'ਹੋਰ ਭਾਸ਼ਾਵਾਂ',
    fewerLanguages: 'ਘੱਟ ਭਾਸ਼ਾਵਾਂ',
    idleHint: 'ਤਿਆਰ',
  },
  'mr-IN': {
    title: 'DirectFarm शी बोला',
    subtitle: 'आवाजाने जवळची पिके शोधा किंवा तुमचे पीक विक्रीस टाका.',
    searchMode: 'पीक शोधा',
    listMode: 'पीक विक्रीस टाका',
    inputLabel: 'पिकाचे नाव किंवा आवाज आदेश',
    placeholderSearch: 'लिहा किंवा माइक दाबा. उदा. "टोमॅटो".',
    placeholderList: 'म्हणा "20 किलो पालक 40 रुपये".',
    tapToSpeak: 'बोलण्यासाठी दाबा',
    listening: 'ऐकत आहे — आता बोला',
    processing: 'तुमचे शब्द समजत आहे…',
    successSearch: 'जवळची शेते शोधत आहोत',
    successList: 'पिकाची माहिती मिळाली',
    errorGeneric: 'आवाज स्पष्ट ऐकू आला नाही. जवळ येऊन पुन्हा प्रयत्न करा.',
    errorDenied: 'आवाज वापरण्यासाठी मायक्रोफोनची परवानगी द्या.',
    errorUnsupported: 'या ब्राउझरमध्ये आवाज उपलब्ध नाही. लिहून शोधा.',
    errorNetwork: 'आवाज सेवा उपलब्ध नाही. नेटवर्क तपासून पुन्हा प्रयत्न करा.',
    stop: 'ऐकणे थांबवा',
    retry: 'पुन्हा प्रयत्न करा',
    examplesSearch: ['टोमॅटो शोधा', 'आंबा दाखवा', 'तांदूळ शोधा'],
    examplesList: ['20 किलो पालक 40 रुपयांना विका', '50 किलो गहू 25 रुपये'],
    confirmList: 'पीक प्रकाशित करा',
    editHint: 'तपशील तपासा, नंतर जवळच्या खरेदीदारांसाठी प्रकाशित करा.',
    name: 'पिकाचे नाव',
    category: 'वर्ग',
    quantity: 'प्रमाण',
    price: 'प्रति एकक किंमत (₹)',
    unit: 'एकक',
    live: 'आम्ही हे ऐकले',
    languageLabel: 'भाषा निवडा',
    moreLanguages: 'अधिक भाषा',
    fewerLanguages: 'कमी भाषा',
    idleHint: 'तयार',
  },
};

export function getVoiceCopy(code) {
  return VOICE_COPY[code] || VOICE_COPY['en-IN'];
}
